port = "9999"

[[servers]]
name = "api01"
host = "localhost"
port = "8080"

[health_check]
interval = 1
endpoint = "/hello"
max_failures = 2

[[servers]]
name = "api02"
host = "localhost"
port = "8081"

